version: '3'

services:

  nginx:
    image: nginx:1.21.1-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/hosts:/etc/nginx/conf.d
      - ./nginx/www:/var/www
      - /var/log/nginx:/var/log/nginx
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    links:
      - php

  php:
    image: php:7.3-fpm-alpine
    container_name: php
    volumes:
      - ./nginx/www:/var/www

  db:
    image: mysql:5.5.60
    container_name: mysql
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ltbot

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    links:
      - db

  certbot:
    image: certbot/certbot
    container_name: certbot
    #restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"